import { jsPDF, GState } from 'jspdf'
import type { NoteSection, ExpectedQuestion, QuizQuestion } from '@/types/generation'

const BRAND = 'StudyForge'
const WATERMARK_TEXT = 'StudyForge'

function createDoc(): jsPDF {
  return new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
}

function addWatermark(doc: jsPDF) {
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  doc.saveGraphicsState()
  doc.setGState(new GState({ opacity: 0.07 }))
  doc.setFontSize(60)
  doc.setTextColor(150, 150, 150)
  doc.setFont('helvetica', 'bold')
  // Diagonal watermark centred on page
  doc.text(WATERMARK_TEXT, pageW / 2, pageH / 2, {
    angle: 45,
    align: 'center',
    baseline: 'middle',
  })
  doc.restoreGraphicsState()
}

function addHeader(doc: jsPDF, title: string) {
  const pageW = doc.internal.pageSize.getWidth()

  // Orange top bar
  doc.setFillColor(249, 115, 22)
  doc.rect(0, 0, pageW, 14, 'F')

  // Brand name — "Study" white, "Forge" white bold
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text(BRAND, 14, 9.5)

  // Document title below the bar
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 30, 30)
  doc.text(title, 14, 26)

  // Thin orange underline
  doc.setDrawColor(249, 115, 22)
  doc.setLineWidth(0.5)
  doc.line(14, 29, pageW - 14, 29)
}

function addFooter(doc: jsPDF, pageNum: number, total: number) {
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  doc.setFontSize(8)
  doc.setTextColor(180, 180, 180)
  doc.setFont('helvetica', 'normal')
  doc.text(`Generated by ${BRAND} · Page ${pageNum} of ${total}`, pageW / 2, pageH - 6, { align: 'center' })
}

function applyWatermarkAndFooterToAllPages(doc: jsPDF) {
  const total = doc.internal.pages.length - 1
  for (let i = 1; i <= total; i++) {
    doc.setPage(i)
    addWatermark(doc)
    addFooter(doc, i, total)
  }
}

// Wraps long text and returns new Y position
function writeWrappedText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxW: number,
  lineHeight: number,
  pageH: number,
  marginBottom: number,
): number {
  const lines = doc.splitTextToSize(text, maxW)
  for (const line of lines) {
    if (y + lineHeight > pageH - marginBottom) {
      doc.addPage()
      addHeader(doc, '')
      y = 36
    }
    doc.text(line, x, y)
    y += lineHeight
  }
  return y
}

export function downloadNotesPDF(sections: NoteSection[]) {
  const doc = createDoc()
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const marginX = 14
  const maxW = pageW - marginX * 2
  const bottomMargin = 18

  addHeader(doc, 'Study Notes')
  let y = 36

  for (const section of sections) {
    // Section heading
    if (y + 10 > pageH - bottomMargin) { doc.addPage(); addHeader(doc, 'Study Notes'); y = 36 }
    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(249, 115, 22)
    doc.text(section.title, marginX, y)
    y += 7

    // Content
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(40, 40, 40)
    y = writeWrappedText(doc, section.content, marginX, y, maxW, 5.5, pageH, bottomMargin)
    y += 3

    // Exam tips
    if (section.exam_tips?.length) {
      if (y + 8 > pageH - bottomMargin) { doc.addPage(); addHeader(doc, 'Study Notes'); y = 36 }
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(180, 80, 0)
      doc.text('Exam Tips', marginX, y)
      y += 5
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(80, 80, 80)
      for (const tip of section.exam_tips) {
        y = writeWrappedText(doc, `• ${tip}`, marginX + 2, y, maxW - 2, 5, pageH, bottomMargin)
      }
      y += 3
    }

    y += 4
  }

  applyWatermarkAndFooterToAllPages(doc)
  doc.save('studyforge-notes.pdf')
}

export function downloadQuestionsPDF(questions: ExpectedQuestion[]) {
  const doc = createDoc()
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const marginX = 14
  const maxW = pageW - marginX * 2
  const bottomMargin = 18

  addHeader(doc, 'Expected Questions')
  let y = 36

  const diffColor: Record<string, [number, number, number]> = {
    easy: [22, 163, 74],
    medium: [202, 138, 4],
    hard: [220, 38, 38],
  }

  questions.forEach((q, i) => {
    if (y + 14 > pageH - bottomMargin) { doc.addPage(); addHeader(doc, 'Expected Questions'); y = 36 }

    // Question number + text
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(30, 30, 30)
    y = writeWrappedText(doc, `${i + 1}. ${q.question}`, marginX, y, maxW, 5.5, pageH, bottomMargin)

    // Meta badges inline
    const [dr, dg, db] = diffColor[q.difficulty] ?? [100, 100, 100]
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(dr, dg, db)
    doc.text(`${q.difficulty.toUpperCase()}  ·  ${q.type}  ·  ${q.marks_weightage}`, marginX + 2, y)
    y += 6

    // Model answer
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(80, 80, 80)
    doc.text('Model Answer:', marginX + 2, y)
    y += 5
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(60, 60, 60)
    y = writeWrappedText(doc, q.model_answer, marginX + 2, y, maxW - 2, 5, pageH, bottomMargin)

    // Key points
    if (q.key_points?.length) {
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(80, 80, 80)
      doc.text('Key Points:', marginX + 2, y)
      y += 5
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(60, 60, 60)
      for (const pt of q.key_points) {
        y = writeWrappedText(doc, `• ${pt}`, marginX + 4, y, maxW - 4, 5, pageH, bottomMargin)
      }
    }

    // Divider
    y += 3
    doc.setDrawColor(220, 220, 220)
    doc.setLineWidth(0.3)
    if (y < pageH - bottomMargin) doc.line(marginX, y, pageW - marginX, y)
    y += 5
  })

  applyWatermarkAndFooterToAllPages(doc)
  doc.save('studyforge-expected-questions.pdf')
}

export function downloadQuizPDF(title: string, questions: QuizQuestion[]) {
  const doc = createDoc()
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  const marginX = 14
  const maxW = pageW - marginX * 2
  const bottomMargin = 18

  addHeader(doc, title || 'Quiz')
  let y = 36

  questions.forEach((q, i) => {
    if (y + 14 > pageH - bottomMargin) { doc.addPage(); addHeader(doc, title || 'Quiz'); y = 36 }

    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(30, 30, 30)
    y = writeWrappedText(doc, `${i + 1}. ${q.question}`, marginX, y, maxW, 5.5, pageH, bottomMargin)

    // Options
    if (q.options?.length) {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      q.options.forEach((opt, j) => {
        const label = String.fromCharCode(65 + j)
        const isCorrect = opt === q.correct_answer
        doc.setTextColor(isCorrect ? 22 : 60, isCorrect ? 163 : 60, isCorrect ? 74 : 60)
        if (isCorrect) doc.setFont('helvetica', 'bold')
        else doc.setFont('helvetica', 'normal')
        y = writeWrappedText(doc, `${label}. ${opt}${isCorrect ? ' ✓' : ''}`, marginX + 4, y, maxW - 4, 5, pageH, bottomMargin)
      })
      y += 2
    } else {
      // Short answer / fill blank — show correct answer
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(22, 163, 74)
      y = writeWrappedText(doc, `Answer: ${q.correct_answer}`, marginX + 4, y, maxW - 4, 5, pageH, bottomMargin)
      y += 2
    }

    // Explanation
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.setTextColor(120, 120, 120)
    y = writeWrappedText(doc, `Explanation: ${q.explanation}`, marginX + 2, y, maxW - 2, 4.8, pageH, bottomMargin)

    y += 3
    doc.setDrawColor(220, 220, 220)
    doc.setLineWidth(0.3)
    if (y < pageH - bottomMargin) doc.line(marginX, y, pageW - marginX, y)
    y += 5
  })

  applyWatermarkAndFooterToAllPages(doc)
  doc.save('studyforge-quiz.pdf')
}
