import { jsPDF, GState } from 'jspdf'
import type { NoteSection, ExpectedQuestion, QuizQuestion } from '@/types/generation'

const BRAND = 'StudyForge'
const WATERMARK_TEXT = 'StudyForge'
const MARGIN_X = 14
const BOTTOM_MARGIN = 18
const LINE_H = 5.5

function createDoc(): jsPDF {
  return new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
}

function pageW(doc: jsPDF) { return doc.internal.pageSize.getWidth() }
function pageH(doc: jsPDF) { return doc.internal.pageSize.getHeight() }
function maxW(doc: jsPDF) { return pageW(doc) - MARGIN_X * 2 }

function addWatermark(doc: jsPDF) {
  doc.saveGraphicsState()
  doc.setGState(new GState({ opacity: 0.06 }))
  doc.setFontSize(58)
  doc.setTextColor(150, 150, 150)
  doc.setFont('helvetica', 'bold')
  doc.text(WATERMARK_TEXT, pageW(doc) / 2, pageH(doc) / 2, {
    angle: 45,
    align: 'center',
    baseline: 'middle',
  })
  doc.restoreGraphicsState()
}

function addHeader(doc: jsPDF, title: string) {
  const w = pageW(doc)
  doc.setFillColor(249, 115, 22)
  doc.rect(0, 0, w, 14, 'F')
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text(BRAND, MARGIN_X, 9.5)
  if (title) {
    doc.setFontSize(18)
    doc.setTextColor(30, 30, 30)
    doc.text(title, MARGIN_X, 26)
    doc.setDrawColor(249, 115, 22)
    doc.setLineWidth(0.5)
    doc.line(MARGIN_X, 29, w - MARGIN_X, 29)
  }
}

function addFooter(doc: jsPDF, pageNum: number, total: number) {
  doc.setFontSize(8)
  doc.setTextColor(180, 180, 180)
  doc.setFont('helvetica', 'normal')
  doc.text(
    `Generated by ${BRAND} · Page ${pageNum} of ${total}`,
    pageW(doc) / 2,
    pageH(doc) - 6,
    { align: 'center' },
  )
}

function applyWatermarkAndFooterToAllPages(doc: jsPDF) {
  const total = doc.internal.pages.length - 1
  for (let i = 1; i <= total; i++) {
    doc.setPage(i)
    addWatermark(doc)
    addFooter(doc, i, total)
  }
}

function checkPageBreak(doc: jsPDF, y: number, needed = LINE_H, title = ''): number {
  if (y + needed > pageH(doc) - BOTTOM_MARGIN) {
    doc.addPage()
    addHeader(doc, title)
    return title ? 36 : 20
  }
  return y
}

function writeLine(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  w: number,
  lh = LINE_H,
  pageTitle = '',
): number {
  const lines = doc.splitTextToSize(text, w)
  for (const line of lines) {
    y = checkPageBreak(doc, y, lh, pageTitle)
    doc.text(line, x, y)
    y += lh
  }
  return y
}

// ── Markdown table renderer ───────────────────────────────────────────────────
function renderTable(
  doc: jsPDF,
  rows: string[][],
  y: number,
  pageTitle: string,
): number {
  const w = maxW(doc)
  const cols = rows[0].length
  const colW = w / cols
  const cellPad = 2
  const rowH = 7

  rows.forEach((row, ri) => {
    y = checkPageBreak(doc, y, rowH + 2, pageTitle)
    const isHeader = ri === 0

    // Row background
    if (isHeader) {
      doc.setFillColor(249, 115, 22)
    } else {
      doc.setFillColor(ri % 2 === 0 ? 250 : 245, ri % 2 === 0 ? 250 : 245, ri % 2 === 0 ? 250 : 245)
    }
    doc.rect(MARGIN_X, y - rowH + 1, w, rowH, 'F')

    // Cell borders
    doc.setDrawColor(220, 220, 220)
    doc.setLineWidth(0.2)
    row.forEach((_, ci) => {
      doc.rect(MARGIN_X + ci * colW, y - rowH + 1, colW, rowH)
    })

    // Cell text
    doc.setFontSize(9)
    doc.setFont('helvetica', isHeader ? 'bold' : 'normal')
    doc.setTextColor(isHeader ? 255 : 40, isHeader ? 255 : 40, isHeader ? 255 : 40)

    row.forEach((cell, ci) => {
      const cellText = cell.trim().replace(/\*\*/g, '')
      const truncated = doc.splitTextToSize(cellText, colW - cellPad * 2)[0] ?? ''
      doc.text(truncated, MARGIN_X + ci * colW + cellPad, y - 1)
    })

    y += rowH
  })

  return y + 2
}

// ── Markdown content renderer ─────────────────────────────────────────────────
function renderMarkdownContent(
  doc: jsPDF,
  content: string,
  y: number,
  pageTitle: string,
): number {
  const w = maxW(doc)
  const lines = content.split('\n')
  let i = 0

  while (i < lines.length) {
    const line = lines[i]

    // Blank line
    if (line.trim() === '') {
      y += 2
      i++
      continue
    }

    // Table: collect all table lines
    if (line.trim().startsWith('|')) {
      const tableLines: string[] = []
      while (i < lines.length && lines[i].trim().startsWith('|')) {
        tableLines.push(lines[i])
        i++
      }
      // Parse rows (skip separator row)
      const rows = tableLines
        .filter((l) => !l.replace(/ /g, '').match(/^\|[-|:]+\|$/))
        .map((l) =>
          l.split('|')
            .slice(1, -1)
            .map((c) => c.trim()),
        )
      if (rows.length > 0) {
        y = renderTable(doc, rows, y, pageTitle)
      }
      continue
    }

    // Heading ### / ## / #
    const headingMatch = line.match(/^(#{1,3})\s+(.+)/)
    if (headingMatch) {
      const level = headingMatch[1].length
      const text = headingMatch[2].replace(/\*\*/g, '')
      y = checkPageBreak(doc, y, 8, pageTitle)
      doc.setFontSize(level === 1 ? 12 : level === 2 ? 11 : 10)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(40, 40, 40)
      y = writeLine(doc, text, MARGIN_X, y, w, LINE_H, pageTitle)
      y += 1
      i++
      continue
    }

    // Numbered list
    const numMatch = line.match(/^(\d+)\.\s+(.+)/)
    if (numMatch) {
      const text = stripInlineMarkdown(numMatch[2])
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(40, 40, 40)
      y = writeLine(doc, `${numMatch[1]}. ${text}`, MARGIN_X + 3, y, w - 3, LINE_H, pageTitle)
      i++
      continue
    }

    // Bullet list - or *
    const bulletMatch = line.match(/^[-*]\s+(.+)/)
    if (bulletMatch) {
      const text = stripInlineMarkdown(bulletMatch[1])
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(40, 40, 40)
      y = writeLine(doc, `• ${text}`, MARGIN_X + 3, y, w - 3, LINE_H, pageTitle)
      i++
      continue
    }

    // Bold line (entire line is **text**)
    if (line.trim().startsWith('**') && line.trim().endsWith('**')) {
      const text = line.trim().slice(2, -2)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(40, 40, 40)
      y = writeLine(doc, text, MARGIN_X, y, w, LINE_H, pageTitle)
      i++
      continue
    }

    // Regular paragraph — strip inline markdown
    const text = stripInlineMarkdown(line)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(40, 40, 40)
    y = writeLine(doc, text, MARGIN_X, y, w, LINE_H, pageTitle)
    i++
  }

  return y
}

function stripInlineMarkdown(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, '$1')   // bold
    .replace(/\*(.+?)\*/g, '$1')        // italic
    .replace(/_(.+?)_/g, '$1')          // underscore italic
    .replace(/`(.+?)`/g, '$1')          // inline code
}

// ── Public export functions ───────────────────────────────────────────────────

export function downloadNotesPDF(sections: NoteSection[]) {
  const doc = createDoc()
  const title = 'Study Notes'
  addHeader(doc, title)
  let y = 36

  for (const section of sections) {
    y = checkPageBreak(doc, y, 10, title)
    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(249, 115, 22)
    y = writeLine(doc, section.title, MARGIN_X, y, maxW(doc), LINE_H, title)
    y += 2

    doc.setTextColor(40, 40, 40)
    y = renderMarkdownContent(doc, section.content, y, title)
    y += 2

    if (section.exam_tips?.length) {
      y = checkPageBreak(doc, y, 8, title)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(180, 80, 0)
      doc.text('Exam Tips', MARGIN_X, y)
      y += 5
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(80, 80, 80)
      for (const tip of section.exam_tips) {
        y = writeLine(doc, `• ${tip}`, MARGIN_X + 2, y, maxW(doc) - 2, 5, title)
      }
    }
    y += 5
  }

  applyWatermarkAndFooterToAllPages(doc)
  doc.save('studyforge-notes.pdf')
}

export function downloadQuestionsPDF(questions: ExpectedQuestion[]) {
  const doc = createDoc()
  const title = 'Expected Questions'
  addHeader(doc, title)
  let y = 36

  const diffColor: Record<string, [number, number, number]> = {
    easy: [22, 163, 74],
    medium: [202, 138, 4],
    hard: [220, 38, 38],
  }

  questions.forEach((q, i) => {
    y = checkPageBreak(doc, y, 14, title)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(30, 30, 30)
    y = writeLine(doc, `${i + 1}. ${q.question}`, MARGIN_X, y, maxW(doc), LINE_H, title)

    const [dr, dg, db] = diffColor[q.difficulty] ?? [100, 100, 100]
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(dr, dg, db)
    doc.text(`${q.difficulty.toUpperCase()}  ·  ${q.type}  ·  ${q.marks_weightage}`, MARGIN_X + 2, y)
    y += 6

    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(80, 80, 80)
    doc.text('Model Answer:', MARGIN_X + 2, y)
    y += 5
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(60, 60, 60)
    y = writeLine(doc, stripInlineMarkdown(q.model_answer), MARGIN_X + 2, y, maxW(doc) - 2, 5, title)

    if (q.key_points?.length) {
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(80, 80, 80)
      doc.text('Key Points:', MARGIN_X + 2, y)
      y += 5
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(60, 60, 60)
      for (const pt of q.key_points) {
        y = writeLine(doc, `• ${stripInlineMarkdown(pt)}`, MARGIN_X + 4, y, maxW(doc) - 4, 5, title)
      }
    }

    y += 3
    doc.setDrawColor(220, 220, 220)
    doc.setLineWidth(0.3)
    const pw = pageW(doc)
    if (y < pageH(doc) - BOTTOM_MARGIN) doc.line(MARGIN_X, y, pw - MARGIN_X, y)
    y += 5
  })

  applyWatermarkAndFooterToAllPages(doc)
  doc.save('studyforge-expected-questions.pdf')
}

export function downloadQuizPDF(title: string, questions: QuizQuestion[]) {
  const doc = createDoc()
  const docTitle = title || 'Quiz'
  addHeader(doc, docTitle)
  let y = 36

  questions.forEach((q, i) => {
    y = checkPageBreak(doc, y, 14, docTitle)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(30, 30, 30)
    y = writeLine(doc, `${i + 1}. ${stripInlineMarkdown(q.question)}`, MARGIN_X, y, maxW(doc), LINE_H, docTitle)

    if (q.options?.length) {
      doc.setFontSize(9)
      q.options.forEach((opt, j) => {
        const label = String.fromCharCode(65 + j)
        const isCorrect = opt === q.correct_answer
        doc.setTextColor(isCorrect ? 22 : 60, isCorrect ? 163 : 60, isCorrect ? 74 : 60)
        doc.setFont('helvetica', isCorrect ? 'bold' : 'normal')
        y = writeLine(doc, `${label}. ${stripInlineMarkdown(opt)}${isCorrect ? ' ✓' : ''}`, MARGIN_X + 4, y, maxW(doc) - 4, 5, docTitle)
      })
      y += 2
    } else {
      doc.setFontSize(9)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(22, 163, 74)
      y = writeLine(doc, `Answer: ${q.correct_answer}`, MARGIN_X + 4, y, maxW(doc) - 4, 5, docTitle)
      y += 2
    }

    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.setTextColor(120, 120, 120)
    y = writeLine(doc, `Explanation: ${stripInlineMarkdown(q.explanation)}`, MARGIN_X + 2, y, maxW(doc) - 2, 4.8, docTitle)

    y += 3
    doc.setDrawColor(220, 220, 220)
    doc.setLineWidth(0.3)
    const pw = pageW(doc)
    if (y < pageH(doc) - BOTTOM_MARGIN) doc.line(MARGIN_X, y, pw - MARGIN_X, y)
    y += 5
  })

  applyWatermarkAndFooterToAllPages(doc)
  doc.save('studyforge-quiz.pdf')
}
